In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.5.1


In [4]:
import numpy as np
list1 = [1,2,3,4,5]
arr = np.array(list1)
print(arr)

[1 2 3 4 5]


In [33]:
import numpy as np
arr1 = np.zeros((2,3),dtype=int)
arr2 = np.ones((2,3),dtype=int)
arr3 = np.full((2,3),3)
print(arr1)
print(arr2)
print(arr3)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]]


In [38]:
np.eye((3),dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [53]:
a = np.arange(1,11)
b = np.linspace(1,10,5)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.    3.25  5.5   7.75 10.  ]


In [59]:
a = np.arange(1,10)
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print("Shape = ",b.shape)
print("Size = ",b.size)
print("Dimension =",b.ndim)
print("Data Type =",b.dtype)

Shape =  (3, 3)
Size =  9
Dimension = 2
Data Type = int64


In [75]:
a = np.random.randint(1,101,10)
print(a)

[45 21 13 76 53 70 44 88 58 41]


In [98]:
import time
list1 = list(range(100000))
start = time.time()
new_list = [i*2 for i in list1]
end = time.time()
print("Python List Time =",end-start)

array1 = np.arange(100000)
start = time.time()
new_array = array1*2
end = time.time()
print("Python Array Time =",end-start)

Python List Time = 0.013958454132080078
Python Array Time = 0.0010247230529785156


In [105]:
arr1 = np.arange(1,11)
print("First Element =",(arr1[0]))
print("Middle Element =",(arr1[4]))
print("Last Element =",(arr1[-1]))

First Element = 1
Middle Element = 5
Last Element = 10


In [110]:
print("First 5 Elements =",(arr1[0:5]))

First 5 Elements = [1 2 3 4 5]


In [112]:
print("Reversed Array =",(arr1[::-1]))

Reversed Array = [10  9  8  7  6  5  4  3  2  1]


In [114]:
arr1 = np.arange(1,13)
arr2 = arr1.reshape(3,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [122]:
arr3 = arr2.flatten()
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [129]:
a = np.array([[1,2,3],
               [4,5,6]])
print("Transpose Matrix")
print(a.T)

Transpose Matrix
[[1 4]
 [2 5]
 [3 6]]


In [133]:
a
print("Row sum =",a.sum(axis=1))
print("Column sum =",a.sum(axis=0))

Row sum = [ 6 15]
Column sum = [5 7 9]


In [135]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print("Vertically")
print(np.vstack((a,b)))
print("Horizontally")
print(np.hstack((a,b)))
            

Vertically
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally
[[1 2 5 6]
 [3 4 7 8]]


In [140]:
a = np.array([10,20,30,40,50,60])
b = np.split(a,3)
print(b)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [143]:
arr1 = np.array([[1,2],
                 [3,4],
                 [5,6]])
print(arr1[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [148]:
a = np.array([8,4,5,1,9])
b = np.array([1,2,3,4,5])
print("Addition =",a+b)
print("Subtraction ",a-b)
print("Multiplication =",a*b)
print("Division =",a//b)

Addition = [ 9  6  8  5 14]
Subtraction  [ 7  2  2 -3  4]
Multiplication = [ 8  8 15  4 45]
Division = [8 2 1 0 1]


In [158]:
a
print("Square =",np.square(a))
print("sqaure Root=",np.sqrt(a))
print("cube =",np.power(a,3))

Square = [64 16 25  1 81]
sqaure Root= [2.82842712 2.         2.23606798 1.         3.        ]
cube = [512  64 125   1 729]


In [163]:
a = np.array([1,2,3,4,5])
print("Maximum =",np.max(a))
print("Minimum =",np.min(a))
print("Average =",np.mean(a))

Maximum = 5
Minimum = 1
Average = 3.0


In [164]:
a = np.array([1,2,3,4,5])
print("sum =",np.sum(a))

sum = 15


In [165]:
a = np.array([1,2,3,4,5])
print("Cumulative Sum =",np.cumsum(a))

Cumulative Sum = [ 1  3  6 10 15]


In [166]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Dot Product =",np.dot(a,b))

Dot Product = 32


In [169]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
print("Matrix Multiplication")
print(np.matmul(a,b))

Matrix Multiplication
[[19 22]
 [43 50]]


In [183]:
b = np.array([[2,3],
             [1,4]],dtype=int)
print("Determinant")
print(np.linalg.det(b))

Determinant
5.000000000000001


In [184]:
print("Inverse Matrix")
print(np.linalg.inv(b))

Inverse Matrix
[[ 0.8 -0.6]
 [-0.2  0.4]]


In [186]:
print("Standard Deviation =",np.std(b))
print("Variance =",np.var(b))

Standard Deviation = 1.118033988749895
Variance = 1.25


In [188]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print("Even Number =",a[a%2==0])

Even Number = [ 2  4  6  8 10]


In [189]:
a
print("Odd Number =",a[a%2!=0])

Odd Number = [1 3 5 7 9]


In [190]:
a = np.array([20,40,60,80])
print("Greater =",a[a>50])

Greater = [60 80]


In [198]:
a = np.array([-1,-2,1,2])
a[a<0]=0
print(a)

[0 0 1 2]


In [200]:
a = np.array([10, 20, 30, 40, 50])
avg = np.mean(a)
count = np.sum(a > avg)
print("Average =", avg)
print("Count =", count)

Average = 30.0
Count = 2


In [201]:
a = np.array([10, 20, 30, 20, 40, 10, 50])
u, c = np.unique(a, return_counts=True)
print(u[c > 1])

[10 20]


In [203]:
a = np.array([10,1,1,1,1,1,13,3,3,3])
print(np.unique(a))

[ 1  3 10 13]


In [204]:
a = np.array([10,20,30,40,50])
print("Ascending:", np.sort(a))
print("Descending:", np.sort(a)[::-1])

Ascending: [10 20 30 40 50]
Descending: [50 40 30 20 10]


In [205]:
a = np.array([30,60,90,120])
print(np.where(a > 75))

(array([2, 3]),)


In [206]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a[a%2==0]=-1
print(a)

[ 1 -1  3 -1  5 -1  7 -1  9 -1]


In [208]:
a = np.random.randint(1,101,50)
print("50 Student Marks =")
print(a)

50 Student Marks =
[32 70 56 95 99 56 51 19 92 97 57 27 64 31 97 43 71  3 28  4 45 50  9 86
 51 80 87 34 10 43 10  7 62  3 69 85 52 10 68 99 38 99 44 79 76 98 31 69
 30 78]


In [211]:
a = np.random.randint(1,101,50)
print("Total =",np.sum(a))
print("Average =",np.mean(a))
print("Highest =",np.max(a))
print("Lowest =",np.min(a))

Total = 2591
Average = 51.82
Highest = 100
Lowest = 1


In [214]:
marks = np.random.randint(0, 101, 50)
print("Above 75 =", np.sum(marks > 75))
print("Below 35 =", np.sum(marks < 35))
print("Between 35 and 75 =", np.sum((marks >= 35) & (marks <= 75)))

Above 75 = 9
Below 35 = 28
Between 35 and 75 = 13


In [217]:
marks = np.array([95, 80, 65, 50, 30])
for i in marks:
    if i >= 75:
        print(i, "A")
    elif i >= 60:
        print(i, "B")
    elif i >= 35:
        print(i, "C")
    else:
        print(i, "Fail")

95 A
80 A
65 B
50 C
30 Fail


In [222]:
marks = np.random.randint(0, 101, 50)
marks = np.sort(marks)
print(marks)
print("TOP 5 Student=",marks[-5:])

[ 1  1  4  6  6 13 17 22 22 23 24 24 25 26 27 31 32 33 33 35 41 42 45 46
 47 49 50 52 52 53 53 53 57 58 59 62 62 65 66 75 82 84 85 88 88 89 90 91
 92 93]
TOP 5 Student= [89 90 91 92 93]


In [227]:
marks = np.random.randint(0, 101, 50)
marks = np.sort(marks)
print(marks)
print("BOTTOM 5 Student=",marks[:5])

[ 2  5  8  9 10 18 22 26 26 29 29 32 37 42 42 44 44 46 47 49 51 55 56 59
 60 64 64 67 70 74 74 77 78 79 80 81 83 86 86 86 88 88 88 91 93 94 96 96
 97 99]
BOTTOM 5 Student= [ 2  5  8  9 10]


In [228]:
marks = np.random.randint(0, 101, 50)
print("Median =", np.median(marks))
print("Standard Deviation =", np.std(marks))

Median = 49.5
Standard Deviation = 29.10631546589159


In [229]:
marks = np.array([[80, 75, 90, 85, 88],
                  [70, 60, 75, 80, 65],
                  [90, 95, 92, 89, 94]])
total = np.sum(marks, axis=1)
print("Marks =")
print(marks)

print("Total =")
print(total)

Marks =
[[80 75 90 85 88]
 [70 60 75 80 65]
 [90 95 92 89 94]]
Total =
[418 350 460]


In [230]:
marks = np.array([[80, 75, 90, 85, 88],
                  [70, 60, 75, 80, 65],
                  [90, 95, 92, 89, 94]])
print(np.max(marks, axis=0))

[90 95 92 89 94]


In [231]:
marks = np.array([80, 75, 90, 85, 88])
total = np.sum(marks)
average = np.mean(marks)
percentage = average
if percentage >= 75:
    grade = "A"
elif percentage >= 60:
    grade = "B"
elif percentage >= 35:
    grade = "C"
else:
    grade = "Fail"
print("Marks =", marks)
print("Total =", total)
print("Average =", average)
print("Percentage =", percentage)
print("Grade =", grade)

Marks = [80 75 90 85 88]
Total = 418
Average = 83.6
Percentage = 83.6
Grade = A
